### ISSUE TITLE
Translator bug?

### ISSUE THREAD

**Issue by Baltazar500** [kingdamian42/AlieneseDecoderReact#1]
![fca48b](https://user-images.githubusercontent.com/12525093/137641861-041a78f0-70be-46ee-b512-be3879d1a705.jpg)

![2021 10 18_05 17 44~01](https://user-images.githubusercontent.com/12525093/137641903-5db79da4-910b-47b6-9f8c-accd8892338e.jpg)

**Comment by kingdamian42** [comment]
Apologies for the time it took for a reply. It appears that this is actually an error in the artwork. If you replace the second to last character with the T looking symbol which is 4 away from the jagged character that made “F” (which should produce E) it works as expected.
